// Word lists for the game.
//
// ANSWERS: curated, common words that can be a solution. No plurals, simple
//          past tenses, proper nouns, or offensive words.
// ALLOWED: every other word that is accepted as a guess.
//
// Built from SCOWL and ENABLE (see NOTICE.md for sources and licenses).
// Words are space-separated and alphabetical so the lists are easy to edit;
// tests/words.test.js checks the format.

const ANSWER_WORDS = `
aback abate abbey abbot abhor abide abode abort about above abuse abyss acorn acrid actor acute
adage adapt adept admit adobe adopt adore adorn adult affix afoot after again agent agile aglow
agony agree ahead aisle alarm album alert alias alibi alien align alike alive allay alley allot
allow alloy aloft alone along aloof aloud alpha altar alter amass amaze amber amble amend amiss
among ample amuse angel anger angle angry angst anime ankle annex annoy annul antic anvil aorta
apart apple apply apron arbor ardor arena argue arise armor aroma arose array arrow arson ashen
aside askew aspen asset atlas atone attic audio audit aural avail avert avoid await awake award
aware awful awoke axiom azure bacon badge badly bagel baggy baker balmy banal bandy banjo barge
baron basic basil basin basis baste batch bathe baton bayou beach beady beard beast beech beefy
befit began begin begun beige belch belie belle belly below bench beret berry berth beset biker
binge bingo biped birch birth bison black blade blame bland blank blare blast blaze bleak bleat
bleed blend bless blimp blind blink bliss blitz block blond blood bloom blown bluff blunt blurb
blurt blush board boast bogus bonus boost booth booze borne bosom bossy botch bough bound boxer
brace braid brain brake brand brash brass brave bravo brawl brawn bread break breed bribe brick
bride brief brine bring brink briny brisk broad broil broke brood brook broom broth brown brunt
brush brute buddy budge buggy bugle build built bulge bulky bully bumpy bunch bunny burly burnt
burst bushy butte buyer cabin cable cacao cache cadet cagey calve camel cameo canal candy canny
canoe canon caper carat cargo carol carry carve caste catch cater caulk cause cease cedar cello
chafe chaff chain chair chalk champ chant chaos charm chart chase chasm cheap cheat check cheek
cheer chess chest chewy chick chide chief child chili chill chime chimp chirp choir choke chord
chore chose chuck chunk churn chute cider cigar cinch circa civic civil clack claim clamp clang
clank clash clasp class clean clear cleat cleft clerk click cliff climb clime cling clink cloak
clock clone close cloth cloud clout clove clown cluck clump clung coach coast cobra cocky cocoa
colic colon color combo comet comfy comic comma condo coral corny corps couch cough could count
coupe court cover covet cower crack craft cramp crane crank crash crass crate crave crawl craze
crazy creak cream creed creek creep crepe crept crest crime crisp croak crock crony crook croon
cross crowd crown crude cruel crumb crush crust crypt cubic curio curly curry curse curve cutie
cycle cynic daddy daily dairy daisy dally dance dandy daunt dealt death debit debug debut decay
decor decoy decry defer deign deity delay delta delve demon denim dense depot depth derby deter
devil diary digit diner dingy dirge dirty disco ditch ditto ditty diver dizzy dodge dogma doily
donor donut dopey doubt dough douse dowdy downy dowry dozen draft drain drake drama drank drape
drawl drawn dread dream dress drift drill drink drive droll drone drool droop dross drove drown
drunk dryer dummy dumpy dunce dusky dusty duvet dwarf dwell dwelt eager eagle early earth easel
eaten eater ebony edict eerie eight eject elbow elder elect elegy elite elope elude email embed
ember emery empty enact endow enemy enjoy ensue enter entry envoy epoch equal equip erase erect
erode error erupt essay ether ethic ethos evade event every evict evoke exact exalt excel exert
exile exist expel extol extra exude exult fable facet faint fairy faith false fancy farce fatal
fault fauna favor feast feign feint felon fence ferry fetch fetid fever fiber field fiend fiery
fifth fifty fight filch filet filly filmy filth final finch first fishy fizzy flail flair flake
flaky flame flank flare flash flask fleck fleet flesh flick fling flint flirt float flock flood
floor flora floss flour flout flown fluff fluid fluke flung flunk flush flute flyer foamy focal
focus foggy foist folly foray force forge forgo forte forth forty forum found fount foyer frail
frame franc frank fraud freak fresh friar frill frisk frock frond front frost froth frown froze
fruit fudge fully funky funny furor furry fussy fuzzy gable gamer gamma gamut gaudy gauge gaunt
gauze gavel gawky genie genre genus ghost ghoul giant giddy girth given glade gland glare glass
glaze gleam glean glide glint gloat globe gloom glory gloss glove gnash gnome godly goner goody
gooey goofy goose gorge gouge gourd grace grade graft grail grain grand grant grape graph grasp
grass grate grave gravy graze great greed green greet grief grill grime grimy grind gripe groan
groin groom gross group grove growl grown gruel gruff grunt guard guess guest guide guild guile
guilt guise gulch gully gummy guppy gusty habit hairy halve handy happy hardy harsh haste hasty
hatch haunt haven havoc hazel heady heard heart heath heave heavy hedge hefty heist hello hence
heron hiker hilly hinge hippy hitch hoard hobby hoist holly homer homey honey honor horde horse
hotel hound house hovel hover huffy human humid humor hunch hurry husky hutch hydra hyena hyper
icing ideal idiom igloo image imply inane inbox incur index indie inept inert infer inlay inlet
inner input intro irate irony issue itchy ivory jaunt jelly jerky jetty jewel jiffy joint joker
jolly judge juice juicy jumbo jumpy junta juror karma kayak khaki kiosk kitty knack knead kneel
knelt knife knock knoll known koala label labor laden ladle lager lance lanky lapel lapse large
larva laser latch later latex lathe latte laugh layer leach leafy leaky learn lease leash least
leave ledge leech leery legal legit lemon levee level lever libel light liken lilac limbo limit
linen liner lingo liter lithe liven liver livid llama loath lobby local lodge lofty logic login
loose loser lotus louse lousy lover lower lowly loyal lucid lucky lumpy lunar lunch lunge lurch
lurid lymph lyric macho macro madam madly magic maize major maker manga mange mango mangy mania
manic manly manor maple march marry marsh mason match matte mauve maxim maybe mayor mealy meant
medal media medic melon mercy merge merit merry messy metal meter metro micro midst might milky
mimic mince miner minor minus mirth miser misty mixer modal model modem moist molar moldy money
month moody moose moral mossy motel motif motor motto mound mount mourn mouse mousy mouth mover
movie mower mucus muddy muggy mulch mummy munch mural murky mushy music musty naive naked nanny
nasal nasty natty naval navel needy neigh nerve never newly nexus niche niece nifty night ninja
ninth noble noise noisy nomad noose north notch novel nudge nurse nutty nylon nymph oasis occur
ocean oddly offer often olden olive omega onion onset opera opium optic orbit order organ other
otter ought ounce outdo outer ovary overt owner oxide ozone pagan pager paint panda panel panic
papal paper parka parse party pasta paste pasty patch patio patty pause payer peace peach pearl
pecan pedal peeve penal penny peony perch peril perky pesky petal petty phase phone phony photo
piano picky piece piety piggy pilot pinch pinky pious piper pique pitch pithy pivot pixel pixie
pizza place plaid plain plane plank plant plate plaza plead pleat pluck plumb plume plump plush
poach point poise poker polar polio polka polyp poppy porch pouch pound power prank prawn preen
press price pride prime print prior prism privy prize probe promo prone prong proof prose proud
prove prowl proxy prude prune psalm psych pudgy puffy pulse punch pupil puppy puree purge purse
pushy putty quack quail quake qualm quark quart quash queen quell query quest queue quick quiet
quill quilt quirk quite quota quote rabbi rabid racer radar radio rainy raise rally ramen ranch
range rapid ratio ratty ravel raven rayon razor reach react ready realm rebel rebut recap recur
refer regal rehab reign relax relay relic remit remix renew repay repel reply reset resin retch
retro retry reuse revel revue rhino rhyme rider ridge rifle right rigid rigor rinse ripen risen
riser risky rival river rivet roach roast robin robot rocky rodeo rogue roomy roost rotor rouge
rough round rouse route rover rowdy royal ruddy rugby ruler rummy rumor runny rural rusty saber
sadly saint salad salon salsa salty salve sandy sassy satin sauce saucy sauna saver savor savvy
scald scale scalp scaly scant scare scarf scary scene scent scoff scold scoop scoot scope score
scorn scour scout scowl scram scrap screw scrub scuba scuff sedan seedy seize sense serum serve
seven sever sewer shack shade shady shaft shake shaky shale shall shame shape share shark sharp
shave shawl sheaf shear sheen sheep sheer sheet shelf shell shift shine shiny shire shirk shirt
shoal shock shone shook shoot shore short shout shove shown showy shred shrew shrub shrug shuck
shunt sidle siege sieve sight sigma silly since sinew singe sinus siren sixth sixty skate skein
skill skimp skirt skulk skull skunk slack slain slang slant slash slate sleek sleep sleet slept
slice slick slide slime slimy sling slink slope slosh sloth slump slung slush smack small smart
smash smear smell smelt smile smirk smite smith smock smoke smoky snack snail snake snare snarl
sneak sneer snide sniff snipe snoop snore snort snout snowy snuff soapy sober soggy solar solid
solve sonar sonic sooty sorry sound south space spade spare spark spasm spate spawn speak spear
speck speed spell spend spent spice spicy spike spill spine spire spite splat split spoil spoke
spoof spook spool spoon spore sport spout spray spree sprig spurn spurt squad squat squid stack
staff stage staid stain stair stake stale stalk stall stamp stand stank stare stark start stash
state stave steak steal steam steel steep steer stein stern stick stiff still sting stink stint
stock stoke stole stomp stone stony stood stool stoop store stork storm story stout stove strap
straw stray strip strum strut stuck study stuff stump stung stunt style suave suede sugar suite
sulky sunny super surge surly sushi swamp swarm swear sweat sweep sweet swell swept swift swill
swine swing swipe swirl swish swoon swoop sword swore sworn swung synth syrup tabby table taboo
tacit tacky taint taken taker tally talon tamer tango taper tardy tarry taste tasty taunt tawny
teach tease teddy tempo tempt tenet tenor tense tenth tepid terse thank theft their theme there
these theta thick thief thigh thing think third thorn those three threw throb throw thumb thump
thyme tiara tidal tiger tight timer timid tinge tipsy titan title toast today token tonal tonic
tooth topaz topic torch torso total totem touch tough towel tower toxic toxin trace track tract
trade trail train trait trash trawl tread treat trend trial tribe trick trill tripe trite troll
troop trout truce truck truly trunk trust truth tulip tummy tumor tuner tunic turbo tutor twang
tweak tweed tweet twice twine twirl twist udder ulcer uncle uncut under undid undue unfit unify
union unite unity untie until upend upper upset urban usage usher usual usurp utter vague valet
valid valor value valve vapor vault vegan venom venue verge verse verve vicar video vigil vigor
villa vinyl viola viper viral virus visit visor vista vital vivid vocal vodka vogue voice voter
vouch vowel wafer wager wagon waist waive waken waltz waste watch water waver weary weave wedge
weedy weigh weird whack whale wharf wheat wheel where which whiff while whine whirl whisk white
whole whoop whose widen widow width wield wince winch windy wiper wispy witch witty woken woman
woody wordy world worry worse worst worth would wound woven wrath wreak wreck wrest wring wrist
write wrong wrote yacht yearn yeast yield yodel yokel young youth yummy zebra
`;

const ALLOWED_WORDS = `
aahed aalii aargh abaca abaci abaft abaka abamp abase abash abbas abbes abeam abele abets abies
abler ables abmho abohm aboil aboma aboon abris abuts abuzz abyes abysm acari acerb aceta ached
aches achoo acids acidy acing acini ackee acmes acmic acned acnes acock acold acred acres acted
actin acyls addax added adder addle adeem adieu adios adits adman admen admin admix adobo adown
adoze adunc adust adyta adzes aecia aedes aegis aeons aerie afars afire afore afoul afrit aftie
aftos agama agape agars agate agave agaze agene agers agger aggie aggro aghas aging agios agism
agist agita aglee aglet agley agmas agone agons agora agria agues ahold ahull aided aider aides
ailed aimed aimer aioli aired airer airns airth airts aitch aiver ajiva ajuga akees akela akene
alack alamo aland alane alang alans alant alary alate albas alcid alder aldol alecs alefs aleph
alfas algae algal algas algid algin algor algum alifs aline alist aliya alkyd alkyl allee allod
allyl almah almas almeh almes almud almug aloes aloha aloin altho altos alula alums alway amahs
amain ambit ambos ambry ameba ameer amens ament amias amice amici amide amido amids amies amiga
amigo amine amino amins amirs amity ammos amnia amnic amnio amoks amole amort amour amped amply
ampul amuck amyls ancon anear anele anent angas anile anils anima animi anion anise ankhs ankus
anlas annal annas annum anoas anode anole anomy anons ansae antae antas anted antes antis antra
antre antsy apace apeak apeek apers apery aphid aphis apian aping apish apnea apods aport appal
appel apres apses apsis apter aptly aquae aquas araks arced arcus ardeb areae areal areas areca
areic arete argal argil argle argol argon argot argus arhat arias ariel arils arles armed armer
armet aroid arpen arras arris arsed arses arsis artal artel artsy arums arval arvos aryls asana
ascot ascus asdic ashed ashes asked asker askoi askos asper aspic aspis assai assay asses aster
astir astro asyla ataps ataxy atilt atman atmas atoll atoms atomy atony atopy atria atrip attar
audad auger aught augur aulic aulos aunts aunty aurae aurar auras aurei aures auric auris aurum
autos auxin avant avast avens avers avgas avian avion aviso avows awash awing awned awols axels
axial axile axils axing axion axite axled axles axman axmen axone axons ayahs ayins azans azide
azido azine azlon azoic azole azons azote azoth baaed baals babas babel babes babka baboo babul
babus bacca baccy backs baddy baels baffs baffy bahts bails bairn baith baits baiza baize baked
bakes balas balds baldy baled baler bales balks balky balls bally balms balsa banco bands baned
banes bangs banks banns banty barbe barbs barde bards bared barer bares barfs baric barks barky
barms barmy barns barny barre barye basal based baser bases basks bassi basso bassy basts bated
bates baths batik batts battu batty bauds baulk bawds bawdy bawls bawty bayed bazar bazoo beads
beaks beaky beams beamy beano beans bears beats beaus beaut beaux bebop becap becks bedel bedew
bedim beefs beeps beers beery beets befog begat beget begot begum beigy being belay belga bells
belts bemas bemix bends bendy benes benne benni benny bento bents bergs berks berme berms beryl
besom besot bests betas betel beths beton betta bevel bevor bevvy bewig bezel bezil bhaji bhang
bhoot bhuts biali bialy bibbs bible bicep bices biddy bided bider bides bidet bield biers biffo
biffs biffy bifid bight bigly bigot bijou biked bikes bikie bilbo biles bilge bilgy bilks bills
billy bimah bimas bimbo binal bindi binds bines binit bints biome biont biota bipod birds birks
birle birls birrs birse bises bisks bitch biter bites bitsy bitts bitty bizes blabs blags blahs
blain blams blase blate blats blawn blaws blear blebs bleep blent blest blets blimy bling blini
blips blite bloat blobs blocs blogs bloke bloop blots blows blowy blubs blued bluer blues bluet
bluey blume blurs blype boars boart boats bobby bocce bocci boche bocks boded bodes bodge boffo
boffs bogan bogey boggy bogie bogle bohea boils boing boite bolar bolas bolds boles bolls bolos
bolts bolus bombe bombs bonce bonds boned boner bones boney bongo bongs bonks bonne bonny bonza
bonze boobs booby booed boogy books booms boomy boong boons boors boots booty boozy borak boral
boras borax bored borer bores boric boron borts borty bortz bosks bosky boson bosun botas botel
bothy botts boule bourg bourn bouse bousy bouts bovid bowed bowel bower bowls bowse boxed boxes
boyar boyla boyos bozos brach bract brads braes brags brail braky brank brans brant brats brava
bravi braws braxy brays braza braze bream brede brees brens brent breve brews briar brier bries
brigs brill brims brins brios brits britt broch brock brome bromo bronc broos brose brosy brows
brugh bruin bruit brume brusk bubal bubba bubby bucko bucks bueno buffi buffo buffs buffy buhls
buhrs bulbs bulgy bulks bulla bulls bumfs bumph bumps bunco bunds bundt bundy bungs bunko bunks
bunns bunts bunya buoys buran buras burbs burds buret burgh burgs burin burka burke burls burns
burps burqa burro burrs burry bursa burse busby bused buses busks busts busty butch buteo butle
butts butty butut butyl buxom bwana bylaw byres byrls byssi bytes byway cabal cabby caber cabob
cacas cacti caddy cades cadge cadgy cadis cadre caeca cafes caffs caged cager cages cahow caids
cains caird cairn cajon caked cakes cakey calfs calif calix calks calla calls calms calyx camas
cames campi campo camps campy caned caner canes canid canna canso canst canto cants canty caped
capes caphs capon capos caput carbo carbs cards cared carer cares caret carex carks carle carls
carns carny carob carom carpi carps carrs carse carte carts casas cased cases casks casky casts
casus cates catty cauda cauld cauls caved caver caves cavie cavil cawed cebid cecal cecum ceded
ceder cedes cedis ceiba ceils celeb cella celli cells celom celts cense cento cents ceorl cepes
cerci cered ceres ceria ceric ceros certs cesar cesta cesti cetes chads chams chang chape chaps
chapt chard chare chark charr chars chary chats chaws chays cheep chefs chela chemo chert cheth
chevy chews chiao chias chico chics chiel chile chimb china chine ching chink chino chins chips
chirk chirm chiro chirr chits chive chivy chock chocs choky choli cholo chomp chook chops chott
chows chubs chufa chuff chugs chump chums churl churr chyle chyme ciaos cibol cilia cimex cines
cions cires cirri cisco cissy cists cited citer cites civet civie civvy clach clade clads clags
clams clans claps clapt claro clary clast clave clavi claws clays cleek clefs clepe clept clews
clift cline clips clipt clits clods clogs clomb clomp clonk clons cloot clops clots clour cloys
cloze clubs clued clues clunk coact coala coals coaly coapt coati coats cobbs cobby cobia coble
cocas cocci cocks cocos codas codec coded coden coder codes codex codon coeds coffs cogon cohog
cohos coifs coign coils coins coirs coked cokes colas colds coled coles coley colin colly colog
colts colza comae comal comas combe combs comer comes comix commy compo comps compt comte conch
coned cones coney conga conge congo conic conin conks conky conns conte conto conus convo cooch
cooed cooee cooer cooey coofs cooks cooky cools cooly coomb coons coops coopt coots copal copay
coped copen coper copes copra copse corby cords cored corer cores corgi coria corks corky corms
corns cornu corse cosec coses coset cosey cosie costa coste costs cotan coted cotes cotta coude
coups couth coved coven coves covey covin cowed cowls cowry coxae coxal coxed coxes coyed coyer
coyly coypu cozen cozes cozey cozie craal crabs crags crake crams crape craps crapy craws credo
creel crees creme crepy cress crews cribs crick cried crier cries crimp crine cripe croci crocs
croft crone cronk crops crore croup crows croze cruck cruds cruet crump cruor crura cruse crwth
cubby cubeb cubed cuber cubes cubit cuddy cuffs cuifs cuing cuish cukes culch culet culex culls
cully culms culpa culti cults cumin cunts cupel cupid cuppa cuppy curbs curch curds curdy cured
curer cures curet curfs curia curie curls curns currs curst curvy cusec cushy cusks cusps cusso
cutch cuter cutes cutey cutin cutis cutty cutup cyano cyans cyber cycad cycas cyclo cyder cylix
cymae cymar cymas cymes cymol cysts cyton czars daces dacha dadas dados daeva daffs daffy dagga
dagos dahls dales daman damar dames damns damps dangs danio darbs dared darer dares daric darks
darky darns darts dashi dashy dated dater dates datos datto datum daube daubs dauby dauts daven
davit dawed dawen dawks dawns dawts dazed dazes deads deair deals deans dears deary deash deave
debag debar debts debus debye decaf decal decks decos dedal deeds deedy deems deeps deers deets
defat defis defog degas degum deice deify deils deism deist deked dekes dekko deled deles delfs
delft delis dells delly demes demit demob demos demur denar denes dents deoxy derat deray derma
derms derry desex desks detox deuce devas devel devon dewan dewar dewax dewed dexes dexie dhaks
dhals dhobi dhole dhoti dhows dhuti dials diazo diced dicer dices dicey dicks dicky dicot dicta
dicty didie didos didst diene diets dight diked diker dikes dikey dildo dills dilly dimer dimes
dimly dinar dined dines dinge dingo dings dinks dinky dints diode diols dippy dipso direr dirks
dirls dirts disci discs dishy disks disme ditas dites ditsy ditzy divan divas dived dives divot
divvy diwan dixie dixit dizen djinn djins doats dobby dobie dobla dobra dobro docks dodgy dodos
doers doest doeth doffs doges dogey doggo doggy dogie doing doits dojos dolce dolci doled doles
dolls dolly dolma dolor dolts domal domed domes domic donas donee donga dongs donna donne donsy
dooly dooms doomy doona doors doozy dopas doped doper dopes dorks dorky dorms dormy dorps dorrs
dorsa dorty dosed doser doses dotal doted doter dotes dotty douce douma doums doura doven doves
dowed dowel dower dowie downs dowse doxie doyen doyly dozed dozer dozes drabs draff drags drail
drams drats drave draws drays drear dreck dreed drees dregs dreks drest dribs dried drier dries
drily drips dript droid droit drops dropt drouk drubs drugs druid drums drupe druse dryad dryly
duads duals ducal ducat duces duchy ducks ducky ducts duddy duded dudes duels duets duffs duits
duked dukes dulia dulls dully dulse dumas dumbo dumbs dumka dumky dumps dunam dunch dunes dungs
dungy dunks dunno dunny dunts duomi duomo duped duper dupes duple duppy dural duras dured dures
durns duroc duros durra durrs durst durum dusks dusts dutch dweeb dwine dyads dyers dying dyked
dykes dykey dynel dynes eagre eared earls earns eased eases easts eaved eaves ebbed ebbet ebons
ebook eched eches echos eclat ecrus edema edged edger edges edify edile edits educe educt effed
egads egers egest eggar egged egger egret eider eidos eikon eking elain eland elans elate elemi
elfin elide elint eloin elute elver elves embar embay embow embus emcee emeer emend emeus emirs
emits emmer emmet emoji emote emyde emyds enate ended ender endue enema ennui enoki enols enorm
enows enrol ensky entia enure envoi enzed enzym eosin epact epees ephah ephas ephod ephor epics
epode epoxy equid ergot erica ernes erose erred erses eruct erugo ervil escar escot eskar esker
esses ester estop etape ethyl etnas etude etuis etwee etyma euros evens evert evils evite ewers
exams exeat execs exine exits exons expat expos exurb eyers eying eyras eyres eyrie eyrir faced
facer faces facia facts faddy faded fader fades fadge fados faena faery faffs faggy fagin fagot
fails fairs faked faker fakes fakey fakir falls famed fames fanes fanga fango fangs fanny fanon
fanos fanum faqir farad farci farcy fards fared farer fares farle farls farms faros farts fasts
fated fates fatly fatso fatty fatwa faugh fauld fauns fauve favas faves favus fawns fawny faxed
faxes fayed fayer fayre fazed fazes fears fease feats feaze fecal feces fecit fecks feeds feels
feeze feist felid fella fells felly felts femes femme femur fends fenny feods feoff feral feres
feria ferly fermi ferns ferny fesse fests fetal fetas feted fetes fetor fetus feuar feuds feued
fewer feyer feyly fezes fiars fiats fibre fices fiche fichu ficin ficus fidge fidos fiefs fifed
fifer fifes filar filed filer files fille fillo fills films filos filum finds fined finer fines
finis finks finny finos fiord fique fired firer fires firms firns firry firth fiscs fists fitch
fitly fiver fives fixed fixer fixes fixit fjeld fjord flabs flack flags flams flamy flans flaps
flats flaws flawy flaxy flays fleam fleas fleer flees flews fleys flics flied flier flies flips
flite flits flocs floes flogs flong flops flory flota flows flubs flued flues fluky flume flump
fluor fluty fluyt flyby flyte foals foams foehn fogey fogie fohns foils foins folds folia folic
folie folio folks folky fonds fondu fonts foods fools foots footy foram forbs forby fordo fords
fores forks forky forme forms forts fossa fosse fouls fourb fours fovea fowls foxed foxes frack
frags fraps frass frats frays freed freer frees fremd frena frere frets fried frier fries frigs
frise frith frits fritt fritz frize frizz froes frogs frons frore frosh frows frugs frump fryer
fubsy fucks fucus fuels fugal fuggy fugio fugle fugue fugus fujis fulls fumed fumer fumes fumet
fundi funds fungi fungo funks furan furls furze furzy fused fusee fusel fuses fusil fusty futon
fuzed fuzee fuzes fuzil fyces fykes fytte gabby gaddi gadid gadis gaffe gaffs gaged gager gages
gaily gains gaits galah galas galax galea gales galls gally galop gamas gamay gamba gambe gambs
gamed games gamey gamic gamin gammy gamps ganef ganev gangs ganja ganof gaols gaped gaper gapes
gappy garbo garbs garni garth gases gasps gassy gasts gated gater gates gator gauds gault gaums
gaurs gauss gauzy gavot gawks gawps gawsy gayal gayer gayly gazar gazed gazer gazes geans gears
gecko gecks geeks geeky geese geest gelds gelee gelid gelts gemma gemmy gemot genes genet genic
genii genip genoa genom genro gents genua geode geoid gerah germs germy gesso geste gests getas
getup geums ghast ghats ghaut ghazi ghees ghyll gibed giber gibes gifts gigas gighe gigot gigue
gilds gills gilly gilts gimel gimme gimps gimpy ginks ginny gipon gipsy girds girls girly girns
giron giros girsh girts gismo gists gites giver gives gizmo glace glads glady glair glans glary
glazy gleba glebe glede gleds gleed gleek glees gleet glens gleys glial glias gliff glime glims
glitz gloam globs glogg gloms glops glost glout glows gloze glued gluer glues gluey glugs glume
gluon gluts glyph gnarl gnarr gnars gnats gnawn gnaws goads goals goats goban gobos godet goers
gofer gogos going golds golem golfs golly gombo gonad gonef gongs gonia gonif gonna gonof gonzo
goodo goods goofs gooks gooky goons goony goops goopy goosy gopak goral gored gores gorps gorse
gorsy goths gotta gouts gouty gowan gowds gowks gowns goxes goyim graal grabs grads grama gramp
grams grana grans grapy grays grebe greek grees grego greys gride grids griff grift grigs grins
griot grips gript gripy grist grith grits groat grogs grope grosz grots grout grows grubs grues
grume grump guaco guano guans guars guava gucks gudes guffs guids guiro gulag gular gulas gules
gulfs gulfy gulls gulps gulpy gumbo gumma gunge gungy gunks gunky gunny gurge gurry gursh gurus
gushy gussy gusto gusts gutsy gutta gutty guyed guyot gybed gybes gypsy gyral gyred gyres gyron
gyros gyrus gyved gyves haafs haars habus hacek hacks hadal haded hades hadji hadst haems haets
hafis hafiz hafts hahas haika haiks haiku hails hairs hajes hajis hajji hakes hakim halal haled
haler hales halid hallo halls halma halms halon halos halts halva hamal hames hammy hamza hance
hands hangs hanks hanky hansa hanse hants haole hapax haply hards hared harem hares harks harls
harms harps harpy harry harts hasps hated hater hates haugh haulm hauls haute haver haves hawed
hawks hawse hayed hayer hazan hazed hazer hazes heads heals heaps hears heats hebes hecks heder
hedgy heeds heels heeze hefts heigh heils heirs helio helix hella hells helms helos helot helps
helve hemal hemes hemic hemin hemps hempy henge henna henry hents herbs herby herds heres herls
herma herms herns heros herry hertz hests heths heuch heugh hewed hewer hexad hexed hexer hexes
hexyl hicks hided hider hides highs hight hijab hiked hikes hilar hillo hills hilts hilum hilus
hinds hinny hints hippo hired hirer hires hissy hists hived hives hoagy hoars hoary hobos hocks
hocus hodad hoers hogan hoggs hoick hoise hoked hokes hokey hokku hokum holds holed holes holey
holks holla hollo holms holts homed homes homie homos honan honda honed honer hones hongs honks
honky hooch hoods hoody hooey hoofs hooka hooks hooky hooly hoons hoops hoots hooty hoped hoper
hopes hoppy horah horal horas horme horns horny horst horsy hosed hosel hosen hoses hosta hosts
hotch hotly hough houri hours howdy howes howff howfs howks howls hoyas hoyle hubby hucks huffs
huger hulas hulks hulky hullo hulls humic humph humps humpy humus hunks hunky hunts hurds hurls
hurly hurst hurts husks hussy huzza hydro hying hylas hymen hymns hyoid hyped hypes hypha hypos
hyrax hyson iambi iambs ichor icier icily icker icons ictic ictus ideas idiot idled idler idles
idols idyll idyls iglus ihram ikats ikons ileac ileal ileum ileus iliac iliad ilial ilium iller
imago imams imaum imbed imbue imide imido imids imine imino immix imped impel impis inapt inarm
inbye incog incus indol indow indri indue infix infos infra ingle ingot inion inked inker inkle
inned innit inset inter intis inure inurn invar iodic iodid iodin ionic iotas irade irids iring
irked iroko irone irons isbas isled isles islet issei istle items ither ivied ivies ixias ixora
ixtle izard izars jabot jacal jacks jacky jaded jades jager jaggs jaggy jagra jails jakes jalap
jalop jambe jambs jammy janes janty japan japed japer japes jarls jatos jauks jaups javas jawan
jawed jazzy jeans jebel jeeps jeers jefes jehad jehus jells jemmy jenny jerid jerks jerry jesse
jests jetes jeton jewed jibbs jibed jiber jibes jiffs jihad jills jilts jimmy jimpy jingo jinks
jinni jinns jisms jived jiver jives jivey jnana jocko jocks joeys johns joins joist joked jokes
jokey joles jolts jolty jones joram jorum jotas jotty joual jouks joule joust jowar jowed jowls
jowly joyed jubas jubes judas judos jugal jugum jujus juked jukes julep jumps junco junks junky
junto jupes jupon jural jurat jurel justs jutes jutty kabab kabar kabob kadis kafir kagus kaiak
kaifs kails kains kakas kakis kalam kales kalif kalis kalpa kames kamik kanas kanes kanga kanji
kanzu kaons kapas kaphs kapok kappa kaput karat karns karoo karst karts kasha katas kauri kaury
kavas kayos kazoo kbars kebab kebar kebob kecks kedge keefs keeks keels keens keeps keets keeve
kefir keirs kelep kelim kelly kelps kelpy kemps kempt kenaf kench kendo kenos kente kepis kerbs
kerfs kerne kerns kerry ketch ketol kevel kevil kexes keyed khadi khafs khans khaph khats kheda
kheth khets khoum kiang kibbe kibbi kibei kibes kibla kicks kicky kiddo kiddy kiefs kiers kikes
kilim kills kilns kilos kilts kilty kinas kinda kinds kines kings kinin kinks kinky kinos kirks
kirns kissy kists kited kiter kites kithe kiths kivas kiwis klong kloof kluge klutz knaps knars
knaur knave kneed knees knell knish knits knobs knops knosp knots knout knows knurl knurs koans
kobos koels kohls koine kolas kolos konks kooks kooky kopek kophs kopje koppa korai korat korma
korun koses kotos kotow kraal kraft krait kraut kreep krill krona krone kroon krubi kudos kudus
kudzu kugel kukri kulak kumys kurta kurus kusso kvass kyack kyaks kyars kyats kyles kylie kylix
kyrie kytes kythe laari labia labra laced lacer laces lacey lacks laded lader lades laevo lagan
lahar laich laics laigh laird lairs laith laity laked laker lakes lakhs lalls lamas lambs lamby
lamed lamer lames lamia lamps lanai lands lanes lapin lapis larch lards lardy laree lares largo
laris larks larky larum lased lases lasso lasts lated laten lathi laths lathy latke lauan lauds
laura lavas laved laver laves lawed lawns lawny laxer laxly layed layup lazar lazed lazes leads
leady leafs leaks leans leant leaps leapt lears leary leavy leben ledgy leeks leers leets lefts
lefty leger leges leggy lehrs lehua leman lemma lemme lemur lends lenes lenis lenos lense lento
leone leper lepta letch lethe letup leuds levin lewis lexes lexis lezzy liana liane liang liard
liars liber libra libri lichi licht licit licks lidar lidos liege liens liers lieus lieve lifer
lifts ligan liger liked liker likes lilly lilos lilts liman limas limba limbi limbs limby limed
limen limes limey limns limos limpa limps linac lindy lined lines liney linga lings lingy linin
links linky linns linos lints linty linum lions lipid lipin lippy liras lirot lisle lisps lists
litai litas litho litre lived lives livre llano loach loads loafs loams loamy loans lobar lobed
lobes lobos lochs locks locos locum locus loden lodes loess lofts logan loges loggy logia logoi
logon logos loins lolls lolly loner longe longs looby looed looey loofa loofs looie looks looms
loons loony loops loopy loots loped loper lopes loppy loral loran lords lores loris lorry losel
loses lossy lotah lotas lotic lotos lotte lotto lough louie louis loupe loups lours loury louts
lovat loved loves lovey lowed lowes lowse loxed loxes luaus lubed lubes lubra luces lucks lucre
ludes ludic luffa luffs luged luger luges lulls lulus lumen lumps lunas lunes lunet lungi lungs
lunks lunts lupin lupus lured lurer lures lurex lurgy lurks lushy lusts lusty lusus lutea luted
lutes luxes lweis lyard lyart lyase lycea lycee lying lynch lyres lysed lyses lysin lysis lyssa
lytic lytta maars mabes macaw maced macer maces mache machs macks macle macon madre mafia mafic
mages magma magot magus mahoe maids maile maill mails maims mains mairs maist makar makes makos
malar males malic malls malms malmy malts malty mamas mamba mambo mamey mamie mamma mammy manas
manat maned manes manky manna manos manse manta manus maqui maras marcs mares marge maria marka
marks marls marly marse marts marvy maser mashy masks massa masse massy masts mated mater mates
matey maths matin matts matza matzo mauds mauls maund mauts maven mavie mavin mavis mawed maxed
maxes maxis mayan mayas mayed mayos mayst mazed mazer mazes mbira meads meals means meany meats
meaty mecca mecha medii meeds meets meiny melds melee melic mells melts memes memos menad mends
mensa mense menta menus meous meows merch merde merer meres merks merle merls mesas meshy mesic
mesne meson meted metes meths metic metis metre mewed mewls mezes mezzo miaou miaow miasm miaul
micas miche micks micra middy midge midis miens miffs miffy miggs miked mikes mikra mikva milch
miler miles milfs milia milks mille mills milos milpa milts milty mimed mimeo mimer mimes minae
minas mincy minds mined mines mingy minim minis minke minks minny mints minty mired mires mirex
mirin mirks mirky mirza misdo mises misos missy mists miter mites mitis mitre mitts mixed mixes
mixup mizen mneme moans moats mocha mocks modes modus moggy mogul mohel mohur moils moira moire
mojos mokes molal molas molds moles molls molly molto molts momes momma mommy momus monad monas
monde mondo mongo monie monks monos monte mooch moods mooed moola mools moons moony moors moory
moots moped moper mopes mopey morae moras moray morel mores morns moron morph morro morse morts
mosey mosks mosso moste mosts motes motet motey moths mothy motte motts mouch moues mould moult
moved moves mowed moxas moxie mozos mucid mucin mucks mucky mucor mucro mudra muffs mufti muggs
muhly mujik mulct muled mules muley mulla mulls multi mumms mumps mumus mungo munis muons muras
mured mures murex murid murks murra murre murrs murry musca mused muser muses musks musky mussy
musth musts mutch muted muter mutes muton mutts muzak muzzy myall mynah mynas myoid myoma myope
myopy myrrh mysid myths mythy naans nabes nabis nabob nacho nacre nadas nadir naevi naggy naiad
naifs nails naira naker nakfa naled named namer names nanas nance nancy napes nappe nappy narco
narcs nards nares naric naris narks narky natal natch nates navar naves navvy nawab nazis neaps
nears neath neats necks needs neems neeps negro negus neifs neist nelly nemas neons neper neral
nerds nerdy nerol nerts nertz nervy nests netop netts netty neuks neume neums neves nevus newel
newer newie newsy newts ngwee nicad nicer nicks nicol nidal nided nides nidus nieve niffy nigga
nighs nihil nills nimbi nimby nines ninny ninon nipas nippy nisei nisus niter nites nitid niton
nitre nitro nitty nival nixed nixes nixie nizam nobby nobly nocks nodal noddy nodes nodus noels
noggs nohow noils noily noirs nolos nomas nomen nomes nomoi nomos nonas nonce nones nonet nongs
nonyl nooks nooky noons nopal noria noris norms nosed noses nosey notal noted noter notes notum
nouns novae novas noway nowts nubby nubia nucha nuder nudes nudie nudzh nuked nukes nulla nulls
numbs numen nurds nurls nutsy nyala oaken oakum oared oases oasts oaten oater oaths oaves obeah
obeli obese obeys obias obits objet oboes obole oboli obols ocher ochre ochry ocker ocrea octad
octal octan octet octyl oculi odder odeon odeum odist odium odors odour odyle odyls oecus ofays
offal offed ofter ogams ogeed ogees ogham ogive ogled ogler ogles ogres ohias ohing ohmic oidia
oiled oiler oinks okapi okays okehs okras older oldie oleic olein oleos oleum olios ollas ology
omasa omber ombre omens omers omits onery onium ontic onyas oohed oomph oorie ootid oozed oozes
opahs opals opens opine oping opsin opted orach orals orang orate orbed orcas orcin ordos oread
orgic oribi oriel orles orlop ormer ornis orpin orris ortho orzos osier osmic osmol ossia ostia
ottar ottos ouija ouphe ouphs ourie ousel ousts outby outed outgo outre outro outta ouzel ouzos
ovals ovate ovens overs ovine ovoid ovoli ovolo ovule owing owlet owned owsen oxbow oxeye oxids
oxime oxims oxlip oxter oyers pacas paced pacer paces pacey pacha packs pacts paddy padis padle
padre padri paean paeon paged pages pagod paiks pails pains pairs paisa paise palea paled paleo
paler pales palet palls pally palms palmy palpi palps palsy pampa pandy paned panes panga pangs
panne pansy panto pants panty papas papaw pappi pappy paras parch pardi pards pardy pared pareo
parer pares pareu parge pargo paris parks parky parle parol parrs parry parts parve parvo paseo
pases pasha pashm passe pasts pated paten pater pates paths patin patly patsy pavan paved paver
paves pavid pavin pavis pawed pawer pawky pawls pawns paxes payed payee payor peage peags peaks
peaky peals peans pears peart pease peats peaty peavy pebas pechs pecks pecky pedes pedro peeks
peels peens peeps peers peery peins peise pekan pekes pekin pekoe peles pelfs pelon pelts pence
pends penes pengo penis penna penne penni peons pepla pepos peppy perdu perdy perea peris perks
perms perry perse pervs pesos pesto pests pesty peter petit petti petto pewee pewit phage pheon
phial phish phlox phono phons phots phpht phuts phyla phyle pians pibal pical picas picks picot
picul piers pieta pigmy piing pikas piked piker pikes pikis pilaf pilar pilau pilaw pilch pilea
piled pilei piles pilis pills pilly pilus pimas pimps pinas pined pines piney pingo pings pinko
pinks pinna pinny pinon pinot pinta pinto pints pinup pions pipal piped pipes pipet pipit pirns
pirog pisco pisos piste pitas piths piton pitta pixes plack plage plait plans plash plasm plats
platy playa plays pleas plebe plebs plena plews plica plied plier plies plink ploce plods plonk
plops plots plotz plows ploys plugs plums plumy plunk plyer pocks pocky poddy podgy podia poems
poesy poets pogey pogge poilu poind poked pokes pokey pokie poled poler poles polis polls polos
polys pomes pommy pomps ponce poncy ponds pones pongs pooch poods pooed poofs poofy poohs pooka
pools poons poops poori poove popes poppa popsy popup pored porer pores porgy porks porky porno
porns porny ports posed poser poses posit posse posts potsy potto potty pouff poufs poult pours
pouts pouty poxed poxes poyou praam prahu prams prana prang praos prase prate prats praus prays
preed prees preps presa prese prest prexy preys prick pricy pried prier pries prigs prill prima
primi primo primp prims prink prion prise priss proas prods proem profs progs prole proms props
proso pross prost prosy proto prows pruta pryer pseud pshaw psoae psoai psoas pubes pubic pubis
puces pucka pucks pudic puffs puggy pujah pujas puked pukes pukka pulas puled puler pules pulik
pulis pulls pulps pulpy pumas pumps punas pungs pungy punka punks punky punny punto punts punty
pupae pupal pupas purda purer purin puris purls purrs pursy puses pussy puton putti putto putts
pwned pygmy pyins pylon pyoid pyran pyres pyric pyxes pyxie pyxis pzazz qaids qanat qibla qophs
quads quaff quags quais quaky quale quant quare quasi quass quate quays quean queer quern queys
quids quiff quins quint quips quipu quire quirt quits quods quoin quoit quoth qursh rabat rabic
raced races racks racon radii radix radon raffs rafts ragas raged ragee rager rages ragga raggy
ragis raias raids rails rains rajah rajas rajes raked rakee raker rakes rakis rales ralph ramee
ramet ramie rammy ramps ramus rance rands randy ranee rangy ranid ranis ranks rants raped raper
rapes raphe rared rarer rares rased raser rases rasps raspy ratal ratan ratch rated ratel rater
rates rathe ratos raved raver raves ravin rawer rawin rawly raxed raxes rayah rayas rayed razed
razee razer razes razoo readd reads reals reams reaps rearm rears reata reave rebar rebbe rebec
rebid rebop rebus rebuy recce recks recon recta recti recto recut redan redds reded redes redia
redid redip redly redon redos redox redry redub redux redye reeds reedy reefs reefy reeks reeky
reels reest reeve refed refel refit refix refly refry reges regex regma regna regos rehem reifs
reify reink reins reive rejig rekey relet relit reman remap remet remex renal rends renes renig
renin rente rents reoil reorg repeg repin repos repot repps repro reran rerig rerun resat resaw
resay resee resew resid resit resod resow rests retag retax retem retia retie revet rewan rewax
rewed rewet rewin rewon rexes rheas rheum rhomb rhumb rhyta rials riant riata ribby ribes riced
ricer rices ricin ricks rides ridgy riels rifer riffs rifts riled riles riley rille rills rimed
rimer rimes rinds rings rinks rioja riots riped riper ripes rises rishi risks risus rites ritzy
rived riven rives riyal roads roams roans roars roate robed robes roble rocks roger roils roily
roles rolfs rolls roman romeo romps ronde rondo roods roofs rooks rooky rooms roose roots rooty
roped roper ropes ropey roque rorts rosed roses roset rosin rotas rotch rotes rotis rotls rotos
rotte rouen roues roups roupy roust routh routs roved roven roves rowan rowed rowel rowen rower
rowth ruana rubel rubes ruble rubus ruche rucks rudds ruder ruers ruffe ruffs rugae rugal ruing
ruins ruled rules rumal rumba rumen rumps runes rungs runic runts runty rupee ruses rushy rusks
rusts ruths rutin rutty ryked rykes rynds ryots sabed sabes sabin sabir sable sabot sabra sabre
sacks sacra sades sadhe sadhu sadis saeta safer safes sagas sager sages saggy sagos sagum sahib
saice saids saiga sails sains saith sajou saker sakes sakis salal salep sales salet salic sally
salmi salol salpa salps salts salvo samba sambo samek sames samey samps sands saned saner sanes
sanga sangh sangs santo sapid sapor sappy saran sards saree sarge sarin saris sarks sarky sarod
saros sasin satay sated satem sates satis satyr sauch saugh sauls sault saury saute saved saves
savin savoy sawed sawer saxes sayer sayid sayst scabs scads scags scall scamp scams scans scape
scarp scars scart scats scatt scaup scaur scena scend schav schmo schul schwa scion scone scops
scots scows scrag scree scrim scrip scrod scrum scudi scudo scuds sculk scull sculp scums scups
scurf scuta scute scuts seals seams seamy sears seats sebum secco sects seder sedge sedgy sedum
seeds seeks seels seely seems seeps seepy seers segni segno segos segue seifs seine seise seism
selah selfs selle sells selva semen semes semis sends sengi senna senor sensa sente senti sepal
sepia sepic sepoy septa septs serac serai seral sered serer seres serfs serge serif serin serow
serry servo setae setal seton setts setup sewan sewar sewed sexed sexes sexto sexts shads shags
shahs shako shalt shaly shams shank shard sharn shaul shawm shawn shaws shays sheal sheas sheds
sheik shend shent sheol sherd shewn shews shied shiel shier shies shill shily shims shins ships
shirr shist shits shiva shive shivs shlep shoat shoed shoer shoes shogs shoji shonk shool shoon
shoos shops shorl shorn shote shots shott shows shoyu shris shtik shuln shuls shuns shush shute
shuts shyer shyly sials sibbs sibyl sices sicko sicks sided sides sieur sifts sighs sigil signs
sikas siker sikes silds silex silks silky sills silos silts silty silva simar simas simba simps
sines sings sinhs sinks siped sipes sired siree sires sirra sirup sisal sises sissy sitar sited
sites situp situs siver sixes sixmo sixte sizar sized sizer sizes skags skald skats skean skeed
skeen skees skeet skegs skelm skelp skene skeps skews skids skied skier skies skiey skiff skimo
skims skink skins skint skips skirl skirr skite skits skive skoal skosh skuas skyed skyey slabs
slags slake slams slank slaps slats slaty slave slaws slays sleds slews slier slily slims slipe
slips slipt slits slobs sloes slogs sloid slojd sloop slops slots slows sloyd slubs slued slues
sluff slugs slums slunk slurb slurp slurs sluts slyer slyly slype smalt smarm smaze smeek smerk
smews smogs smoko smolt smote smuts snafu snags snaky snaps snark snash snath snaws sneap sneck
sneds snell snibs snick snips snits snobs snogs snood snook snool snoot snots snows snubs snuck
snugs snyes soaks soaps soare soars soave socko socks socle sodas soddy sodic sodom sofar sofas
softa softs softy soils sojas sokes sokol solan soldi soldo soled solei soles solon solos solum
solus somas sonde sones songs sonly sonny sonsy sooey sooks sooky sooth soots sophs sophy sopor
soppy soras sorbs sords sorel sorer sores sorgo sorns sorta sorts sorus soths sotol sough souks
souls soups soupy sours souse sowar sowed sower soyas soyuz sozin spacy spado spaed spaes spahi
spail spait spake spale spall spams spang spank spans spars spats spays spean specs speel speer
speil speir spelt speos sperm spews spica spick spics spied spiel spier spies spiff spiks spiky
spile spilt spins spiny spirt spiry spits spitz spivs splay spode spoor spots sprag sprat sprit
sprog sprue sprug spuds spued spues spume spumy spunk spurs sputa squab squaw squeg squib sruti
stabs stade stags stagy staig stane stang staph stars stats stays stead steed steek stela stele
stems steno stent steps stere stets stews stich stied sties stile stilt stime stimy stipe stirk
stirp stirs stoae stoai stoas stoat stobs stogy stoic stoma stook stope stops stopt stoss stoup
stour stowp stows stree strep strew stria strop strow stroy stubs studs stull stums stunk stuns
stupa stupe sturt styed styes styli stymy subah subas suber sucks sucre sudds sudor sudsy suers
suets suety sughs suing suint suits sulci sulfa sulfo sulks sully sulus sumac summa sumos sumps
sunna sunns sunup supes supra surah sural suras surds surer surfs surfy surgy surra sutra sutta
swabs swage swags swail swain swale swami swamy swang swank swans swaps sward sware swarf swart
swash swath swats sways swede sweer swigs swims swink swiss swith swive swizz swobs swops swots
swoun sycee syces sykes sylis sylph sylva synch syncs synod syphs syren sysop taber tabes tabid
tabla tabor tabun tabus taces tacet tache tachs tacks tacos tacts taels taffy tafia tahrs taiga
tails tains tajes takas takes takin talar talas talcs taler tales talks talky taluk talus tamal
tamed tames tamis tammy tamps tangs tangy tanka tanks tansy tanto tapas taped tapes tapir tapis
tardo tared tares targe tarns taroc tarok taros tarot tarps tarre tarsi tarts tarty taser tasks
tasse tatar tater tates tatty taupe tauts tawed tawer tawie tawse taxed taxer taxes taxis taxon
taxus tayra tazza tazze teaks teals teams tears teary teats techs techy tecta teels teems teens
teeny teeth teffs tegua teiid teind telae teles telex telia telic tells telly teloi telos tempi
temps tench tends tenge tenia tenno tenon tents tenty tepal tepas tepee tepoy terai terce terga
terms terne terns terra terry tesla testa tests testy teths tetra teuch teugh tewed texas texts
thack thane tharm thaws thebe theca thees thegn thein thens therm thews thewy thill thine thins
thiol thirl thole thong thoro thorp thous thraw thrip throe thrum thuds thugs thuja thunk thurl
thuya thymi thymy tibia tical ticks tided tides tiers tiffs tigon tikes tikis tilak tilde tiled
tiler tiles tills tilth tilts timed times tinct tinea tined tines tings tinny tints tipis tippy
tired tires tirls tiros titch titer tithe titis titre titty tizzy toads toady toddy toeas toffs
toffy tofts tofus togae togas togue toile toils toits tokay toked toker tokes tolan tolar tolas
toled toles tolls tolly tolus tolyl toman tombs tomes tommy tondi tondo toned toner tones toney
tonga tongs tonne tonus tools toons toots toped topee toper topes tophe tophi tophs topis topoi
topos toque torah toras torcs tores toric torii toros torot torrs torse torsi torsk torte torts
torus toted toter totes tours touse touts towed towie towns towny toyed toyer toyon toyos tragi
traik tramp trams trank tranq trans traps trapt trass trave trays treed treen trees treks tress
trets trews treys triac triad trice tried trier tries trigo trigs trike trims trine triol trios
trips troak troat trock trode trois troke tromp trona trone trooz trope troth trots trove trows
troys trued truer trues trugs trull trump truss tryma tryst tsade tsadi tsars tsked tsuba tubae
tubal tubas tubby tubed tuber tubes tucks tufas tuffs tufts tufty tules tulle tumid tumps tunas
tuned tunes tungs tunny tupik tuple tuque turds turfs turfy turks turns turps tushy tusks tutee
tutti tutty tutus tuxes tuyer twaes twain twats tween twerk twerp twier twigs twill twink twins
twiny twirp twits twixt twyer tyees tyers tying tykes tyned tynes typal typed types typey typic
typos typps tyred tyres tyros tythe tzars uhlan ukase ulama ulans ulema ulnad ulnae ulnar ulnas
ulpan ultra ulvas umbel umber umbos umbra umiac umiak umiaq umped unais unapt unarm unary unaus
unban unbar unbid unbox uncap uncia uncos uncoy uncus undee unfed unfix ungot unhat unhip units
unjam unlay unled unlet unlit unman unmet unmew unmix unpeg unpen unpin unrig unrip unsay unset
unsew unsex unwed unwit unwon unzip upbow upbye updos updry uplit upped uraei urare urari urase
urate urbia ureal ureas uredo ureic urged urger urges urial urine ursae users using usnea usque
usury uteri utile uveal uveas uvula vacua vagal vagus vails vairs vakil vales valse vamps vampy
vanda vaned vanes vangs vaped vapes vapid varas varia varix varna varus varve vasal vases vasts
vasty vatic vatus vaunt veals vealy vedic veena veeps veers veery veges vegie veils veins veiny
velar velds veldt velum venae venal vends venge venin vents verbs verey versa verso verst verts
vertu vesta vests vetch veter vexed vexer vexes vexil vials viand vibes viced vices vichy viers
views viewy vigas viler villi vills vimen vinal vinas vinca vined vines vinic vinos viols vireo
vires virga virid virls virtu visas vised vises vitae vitta vivas vixen vizir vizor vlogs voces
vodun vogie voids voila voile volar voled voles volta volte volti volts volva vomer vomit voted
votes vouge vowed vower vroom vrouw vrows vuggs vuggy vughs vulgo vulva vying wacke wacko wacks
wacky waddy waded wader wades wadge wadis waffs wafts waged wages wahoo waifs wails wains wairs
waits waked waker wakes waled waler wales walks walla walls wally wames wamus wands waned wanes
waney wanks wanly wanna wants wards wared wares warks warms warns warps warts warty washy wasps
waspy wasts watap watts waugh wauks wauls waved waves wavey wawls waxed waxen waxer waxes wazoo
weald weals weans wears webby weber wecht wedel wedgy weeds weeks weens weeny weeps weepy weest
weets wefts weirs wekas welch welds wells welly welsh welts wench wends wenny wersh wests wetly
whamo whams whang whaps whats whaup wheal wheen wheep whelk whelm whelp whens whets whews wheys
whids whigs whims whins whiny whips whipt whirr whirs whish whist whits whity whizz whomp whoof
whops whore whorl whort whoso whump whups wicks widdy wider wides wifed wifes wifty wigan wiggy
wight wikis wilco wilds wiled wiles wills willy wilts wimps wimpy winds wined wines winey wings
wingy winks winos winze wiped wipes wired wirer wires wirra wised wisen wiser wises wisha wisps
wists witan wited wites withe withy wived wiver wives wizen wizes woads woald wodge woful wolds
wolfs wombs womby women wonks wonky wonts woods wooed wooer woofs wools wooly woops woosh woozy
words works worms wormy worts wowed wrack wrang wraps wrapt wrens wrick wried wrier wries writs
wroth wrung wryer wryly wurst wussy wyled wyles wynds wynns wyted wytes xebec xenia xenic xenon
xeric xerox xerus xylan xylem xylol xylyl xysti xysts yabby yacks yaffs yager yagis yahoo yaird
yakka yamen yamun yangs yanks yapok yapon yappy yards yarer yarns yauds yauld yaups yawed yawls
yawns yawps yeahs yeans years yecch yechs yechy yeggs yelks yells yelps yenta yente yerba yerks
yeses yetis yetts yeuks yeuky yikes yills yince yipes yirds yirrs yirth ylems yobbo yocks yodhs
yodle yogas yogee yoghs yogic yogin yogis yoked yokes yolks yolky yomim yonic yonis yonks yores
yourn yours youse yowed yowes yowie yowls yuans yucas yucca yucch yucks yucky yugas yukky yulan
yules yupon yurta yurts zacks zaire zamia zanza zappy zarfs zaxes zayin zazen zeals zebec zebus
zeins zerks zeros zests zesty zetas zibet zilch zills zincs zincy zineb zines zings zingy zinky
zippy ziram zitis zizit zlote zloty zoeae zoeal zoeas zombi zonal zoned zoner zones zonks zooid
zooks zooms zoons zooty zoril zoris zowie zymes
`;

const parse = (text) => text.trim().split(/\s+/);

export const ANSWERS = parse(ANSWER_WORDS);
export const ALLOWED = parse(ALLOWED_WORDS);
